@startuml vpc-er-diagram

' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

entity "VPC" as vpc {
    *vpc_id: varchar <<generated>>
    --
    cidr_block: varchar
    owner_id: varchar
}

entity "AvailabilityZone" as av {
  *availability_zone_id: varchar
}

entity "SubNet" as subnet {
    *subnet_id: varchar
    --
    name: varchar
    vpc_id: varchar
    availability_zone_id: varchar
    cidr_block: varchar
    owner_id: varchar
}

entity "InternetGW" as igw {
    *igw_id: varchar
    --
    vpc_id: varchar
}

entity "RouteTable" as routetable {
    *routetable_id: varchar
    --
    name: varchar
    vpc_id: varchar
    subnet_id: varchar
}

entity "Route" as route {
  *rotetable_id: varchar
  *destination_ip: varchar
  --
  target_type: varchar
  taget_igw_id: varchar
  
}

vpc ||..o{ subnet
vpc |o..o{ igw
vpc ||..o{ routetable
av ||..o{subnet
subnet |o..o| routetable
routetable ||..o{route
igw |o..o{route
@enduml
